# Generated by Django 4.2.11 on 2026-06-22 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_customers', models.IntegerField()),
                ('new_customers', models.IntegerField()),
                ('repeat_customers', models.IntegerField()),
                ('customer_retention_rate', models.FloatField()),
                ('average_customer_lifetime_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('top_customer', models.CharField(blank=True, max_length=255)),
                ('top_customer_spend', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_loyalty_points_redeemed', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'customer_analytics',
            },
        ),
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_transactions', models.IntegerField(default=0)),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('total_discount_given', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('upi_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('top_product', models.CharField(blank=True, max_length=255)),
                ('top_product_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'daily_sales_reports',
            },
        ),
        migrations.CreateModel(
            name='InventoryValuationReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('total_medicines', models.IntegerField()),
                ('total_quantity_on_hand', models.IntegerField()),
                ('total_stock_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('medicines_expiring_30_days', models.IntegerField()),
                ('medicines_expiring_90_days', models.IntegerField()),
                ('dead_stock_count', models.IntegerField(help_text='No movement in 90+ days')),
                ('dead_stock_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low_stock_items', models.IntegerField()),
                ('inventory_turnover_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory_valuation_reports',
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kpi_name', models.CharField(max_length=255)),
                ('kpi_value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20)),
                ('measurement_date', models.DateField()),
                ('status', models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('CRITICAL', 'Critical')], max_length=20)),
            ],
            options={
                'db_table': 'kpis',
            },
        ),
        migrations.CreateModel(
            name='ProfitLossReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost_of_goods', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_margin_percent', models.FloatField()),
                ('operating_margin_percent', models.FloatField()),
                ('net_margin_percent', models.FloatField()),
            ],
            options={
                'db_table': 'profit_loss_reports',
            },
        ),
        migrations.CreateModel(
            name='SalesAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('category', models.CharField(max_length=255)),
                ('medicine_name', models.CharField(blank=True, max_length=255)),
                ('quantity_sold', models.IntegerField()),
                ('total_sales_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gross_margin_percent', models.FloatField()),
            ],
            options={
                'db_table': 'sales_analytics',
            },
        ),
    ]
