# Generated by Django 4.2.11 on 2026-06-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesanalytics',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.branch'),
        ),
        migrations.AddField(
            model_name='salesanalytics',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_analytics', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='profitlossreport',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.branch'),
        ),
        migrations.AddField(
            model_name='profitlossreport',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_reports', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.branch'),
        ),
        migrations.AddField(
            model_name='kpi',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='inventoryvaluationreport',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.branch'),
        ),
        migrations.AddField(
            model_name='inventoryvaluationreport',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reports', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales_reports', to='pharmacy.branch'),
        ),
        migrations.AddField(
            model_name='dailysalesreport',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales_reports', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='customeranalytics',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_analytics', to='pharmacy.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='salesanalytics',
            index=models.Index(fields=['pharmacy', 'period_start', 'period_end'], name='sales_analy_pharmac_5b8e8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profitlossreport',
            unique_together={('pharmacy', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['pharmacy', 'measurement_date'], name='kpis_pharmac_ad2b42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryvaluationreport',
            unique_together={('pharmacy', 'branch', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='dailysalesreport',
            index=models.Index(fields=['pharmacy', 'report_date'], name='daily_sales_pharmac_e7e2ed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysalesreport',
            unique_together={('pharmacy', 'branch', 'report_date')},
        ),
    ]
