# Generated by Django 4.2.11 on 2026-06-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('inventory', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinebatch',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseorder'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='shelf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.shelf'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='inventory.medicinecategory'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicines', to='inventory.manufacturer'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pharmacy.branch'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.medicine'),
        ),
        migrations.AddField(
            model_name='genericmapping',
            name='brand_medicines',
            field=models.ManyToManyField(related_name='generic_mappings', to='inventory.medicine'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch', 'created_at'], name='inventory_s_branch__377a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['medicine', 'movement_type'], name='inventory_s_medicin_244574_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['branch', 'expiry_date'], name='inventory_m_branch__c412c1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['medicine', 'is_depleted'], name='inventory_m_medicin_a46bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinebatch',
            index=models.Index(fields=['supplier', 'created_at'], name='inventory_m_supplie_62bec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(check=models.Q(('quantity_received__gte', 0)), name='batch_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(check=models.Q(('quantity_available__gte', 0)), name='batch_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(check=models.Q(('quantity_damaged__gte', 0)), name='batch_damaged_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(check=models.Q(('quantity_expired__gte', 0)), name='batch_expired_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__gte', 0)), name='batch_purchase_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(check=models.Q(('selling_price__gte', 0)), name='batch_selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicinebatch',
            constraint=models.CheckConstraint(check=models.Q(('expiry_date__gt', models.F('manufacturing_date'))), name='batch_expiry_after_mfg'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinebatch',
            unique_together={('medicine', 'branch', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['generic_name'], name='inventory_m_generic_acb93c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['brand_name'], name='inventory_m_brand_n_82f012_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['sku'], name='inventory_m_sku_f55e64_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['barcode'], name='inventory_m_barcode_e0e768_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['is_active', 'created_at'], name='inventory_m_is_acti_e8ee0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('quantity_per_pack__gt', 0)), name='medicine_quantity_per_pack_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__gte', 0)), name='medicine_purchase_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('selling_price__gte', 0)), name='medicine_selling_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('mrp__gte', 0)), name='medicine_mrp_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('reorder_level__gte', 0)), name='medicine_reorder_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.CheckConstraint(check=models.Q(('maximum_stock_level__gte', 0)), name='medicine_max_stock_non_negative'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['branch', 'total_quantity'], name='inventory_i_branch__ea5d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['medicine', 'updated_at'], name='inventory_i_medicin_cd9999_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('total_quantity__gte', 0)), name='inventory_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('available_quantity__gte', 0)), name='inventory_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__gte', 0)), name='inventory_reserved_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('medicine', 'branch')},
        ),
    ]
