services:
  - type: redis
    name: pharmacy-redis
    ipAllowList: []
    plan: free

  - type: web
    name: pharmacy-django
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py migrate"
    startCommand: "cd backend && daphne -b 0.0.0.0 -p $PORT config.asgi:application"
    envVars:
      - key: DB_NAME
        value: "postgres"
      - key: DB_USER
        value: "postgres.ftlvatwrxywdfedzywvw"
      - key: DB_PASSWORD
        value: "JWTcypYyE0HKRtTx"
      - key: DB_HOST
        value: "aws-0-us-east-1.pooler.supabase.com"
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        fromService:
          type: redis
          name: pharmacy-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: pharmacy-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings"
    plan: free

  - type: worker
    name: pharmacy-celery
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && celery -A config worker -l info"
    envVars:
      - key: DB_NAME
        value: "postgres"
      - key: DB_USER
        value: "postgres.ftlvatwrxywdfedzywvw"
      - key: DB_PASSWORD
        value: "JWTcypYyE0HKRtTx"
      - key: DB_HOST
        value: "aws-0-us-east-1.pooler.supabase.com"
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        fromService:
          type: redis
          name: pharmacy-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: pharmacy-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings"
    plan: free
