services:
  - type: redis
    name: pharmacy-redis
    ipAllowList: []
    plan: free

  - type: web
    name: pharmacy-django
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && bash run.sh"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: pharmacy-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: pharmacy-redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings"
    plan: free

  - type: worker
    name: pharmacy-celery
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && celery -A config worker -l info"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: pharmacy-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: pharmacy-redis
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings"
    plan: free
