# Generated by Django 4.2.11 on 2026-06-22 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreport',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_reports', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.branch'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='pharmacy.pharmacy'),
        ),
        migrations.AlterUniqueTogether(
            name='taxreport',
            unique_together={('pharmacy', 'tax_type', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['pharmacy', 'entry_date'], name='journal_ent_pharmac_862d79_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['reference_type', 'reference_number'], name='journal_ent_referen_5a7a19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generalledger',
            unique_together={('account', 'period_date')},
        ),
        migrations.AddIndex(
            model_name='chartofaccounts',
            index=models.Index(fields=['pharmacy', 'account_type'], name='chart_of_ac_pharmac_147126_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccounts',
            unique_together={('pharmacy', 'account_code')},
        ),
    ]
