# Generated by Django 4.2.11 on 2026-06-22 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], max_length=50)),
                ('recipient_identifier', models.CharField(help_text='Phone, email, or user ID', max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('provider_response', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pharmacy.pharmacy')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('EXPIRY_ALERT', 'Expiry Alert'), ('REFILL_DUE', 'Refill Due'), ('ORDER_CONFIRMATION', 'Order Confirmation'), ('DELIVERY_UPDATE', 'Delivery Update'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('LOYALTY_POINTS', 'Loyalty Points Update'), ('PROMOTION', 'Promotion'), ('CUSTOM', 'Custom Message')], max_length=50)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', 'In-App')], max_length=20)),
                ('subject', models.CharField(blank=True, help_text='For email', max_length=255)),
                ('template_text', models.TextField(help_text='Use {{variable}} for placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='pharmacy.pharmacy')),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('pharmacy', 'trigger_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('expiry_alerts', models.BooleanField(default=True)),
                ('refill_reminders', models.BooleanField(default=True)),
                ('order_updates', models.BooleanField(default=True)),
                ('delivery_updates', models.BooleanField(default=True)),
                ('promotional_offers', models.BooleanField(default=False)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['pharmacy', 'status'], name='notificatio_pharmac_db1c41_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
    ]
