# Generated by Django 4.2.8 on 2026-06-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('PASSWORD_RESET', 'Password Reset'), ('SUPERUSER_PROMOTION', 'Superuser Promotion'), ('SUPERUSER_DEMOTION', 'Superuser Demotion'), ('STAFF_INVITATION', 'Staff Invitation')], max_length=30),
        ),
    ]
