# Generated by Django 4.2.11 on 2026-06-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_branches',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_devices_per_branch',
            field=models.IntegerField(default=1),
        ),
    ]
