# Generated by Django 4.2.11 on 2026-06-22 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctor_profiles',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('allergies', models.JSONField(default=list, help_text='List of known allergies')),
                ('chronic_conditions', models.JSONField(default=list, help_text='Pre-existing conditions')),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription_number', models.CharField(max_length=100, unique=True)),
                ('prescription_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FILLED', 'Filled'), ('PARTIALLY_FILLED', 'Partially Filled'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('is_controlled_drug', models.BooleanField(default=False, help_text='Schedule H or X drug requiring special handling')),
                ('is_repeat_prescription', models.BooleanField(default=False)),
                ('max_refills', models.IntegerField(default=0)),
                ('refills_remaining', models.IntegerField(default=0)),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='prescriptions/%Y/%m/%d/')),
                ('ocr_text', models.TextField(blank=True, help_text='OCR extracted text from prescription image')),
                ('ocr_confidence', models.FloatField(default=0, help_text='OCR confidence score 0-1')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_filled_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.branch')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='prescriptions.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='prescriptions.patientprofile')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacy.pharmacy')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_prescribed', models.IntegerField()),
                ('quantity_filled', models.IntegerField(default=0)),
                ('dosage_instructions', models.TextField(help_text="e.g., '1 tablet twice daily after meals'")),
                ('duration_days', models.IntegerField(blank=True, help_text='Number of days for which medicine prescribed', null=True)),
                ('special_instructions', models.TextField(blank=True, help_text="e.g., 'Do not take with milk'")),
                ('substitution_allowed', models.BooleanField(default=False, help_text='Can pharmacist substitute with generic?')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('VERIFIED', 'Verified'), ('FILLED', 'Filled'), ('REFILLED', 'Refilled'), ('CANCELLED', 'Cancelled'), ('STATUS_CHANGED', 'Status Changed')], max_length=50)),
                ('change_details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'prescription_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['phone'], name='patient_pro_phone_504a73_idx'),
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['email'], name='patient_pro_email_291c47_idx'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='pharmacy.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['prescription', 'medicine'], name='prescriptio_prescri_ab1b06_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['pharmacy', 'prescription_number'], name='prescriptio_pharmac_2260fb_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='prescriptio_patient_e097dd_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['expiry_date'], name='prescriptio_expiry__bbf7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['pharmacy', 'registration_number'], name='doctor_prof_pharmac_90153f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['email'], name='doctor_prof_email_ef73c4_idx'),
        ),
    ]
