# Generated by Django 4.2.11 on 2026-06-22 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('allergies', models.JSONField(default=list)),
                ('chronic_conditions', models.JSONField(default=list)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('insurance_provider', models.CharField(blank=True, max_length=255)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_validity_date', models.DateField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loyalty_balance', models.DecimalField(decimal_places=2, default=0, help_text='Loyalty points or cash balance', max_digits=12)),
                ('sms_consent', models.BooleanField(default=True)),
                ('email_consent', models.BooleanField(default=True)),
                ('whatsapp_consent', models.BooleanField(default=False)),
                ('push_notification_consent', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='pharmacy.pharmacy')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Points Earned'), ('REDEEMED', 'Points Redeemed'), ('EXPIRED', 'Points Expired'), ('ADJUSTED', 'Manual Adjustment')], max_length=20)),
                ('points_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_id', models.CharField(blank=True, help_text='Link to sale transaction', max_length=100, null=True)),
                ('description', models.TextField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='customers.customer')),
            ],
            options={
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_per_rupee', models.FloatField(default=1.0, help_text='How many points earned per rupee spent')),
                ('redemption_rate', models.FloatField(default=1.0, help_text='How many rupees worth of discount per point redeemed')),
                ('tier_bronze_min', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tier_silver_min', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('tier_gold_min', models.DecimalField(decimal_places=2, default=25000, max_digits=12)),
                ('tier_platinum_min', models.DecimalField(decimal_places=2, default=100000, max_digits=12)),
                ('tier_bronze_discount', models.FloatField(default=0, help_text='Extra discount % for tier')),
                ('tier_silver_discount', models.FloatField(default=2)),
                ('tier_gold_discount', models.FloatField(default=5)),
                ('tier_platinum_discount', models.FloatField(default=10)),
                ('points_expiry_days', models.IntegerField(default=365)),
                ('is_active', models.BooleanField(default=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='pharmacy.pharmacy')),
            ],
            options={
                'db_table': 'loyalty_programs',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work'), ('OTHER', 'Other')], default='HOME', max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_addresses',
            },
        ),
        migrations.CreateModel(
            name='CustomerPrescriptionHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_brand', models.CharField(blank=True, max_length=255)),
                ('dosage_instructions', models.TextField(blank=True)),
                ('last_purchased_date', models.DateTimeField()),
                ('refill_due_date', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(help_text='e.g., Daily, Weekly, Monthly', max_length=100)),
                ('doctor_name', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_history', to='customers.customer')),
            ],
            options={
                'db_table': 'customer_prescription_history',
                'indexes': [models.Index(fields=['customer', 'last_purchased_date'], name='customer_pr_custome_cf6e9e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['pharmacy', 'phone'], name='customers_pharmac_092666_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_vip', 'created_at'], name='customers_is_vip_dff2ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('credit_limit__gte', 0)), name='customer_credit_limit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('outstanding_balance__gte', 0)), name='customer_outstanding_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(check=models.Q(('loyalty_balance__gte', 0)), name='customer_loyalty_non_negative'),
        ),
    ]
