# Generated by Django 4.2.11 on 2026-06-22 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('opening_time', models.TimeField(default='08:00:00')),
                ('closing_time', models.TimeField(default='22:00:00')),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.customuser')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_expiry', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='common.customuser')),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_id', models.CharField(max_length=50)),
                ('tax_registration_date', models.DateField()),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_registered', models.BooleanField(default=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_config', to='pharmacy.pharmacy')),
            ],
            options={
                'verbose_name': 'Tax Configuration',
                'verbose_name_plural': 'Tax Configurations',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_type', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issuing_authority', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='licenses/')),
                ('is_active', models.BooleanField(default=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='pharmacy.pharmacy')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('low_stock_value', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('minimum_sale_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maximum_discount_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('bill_footer_text', models.TextField(blank=True)),
                ('bill_header_text', models.TextField(blank=True)),
                ('enable_credit_billing', models.BooleanField(default=True)),
                ('enable_wallet_billing', models.BooleanField(default=True)),
                ('low_stock_alert_enabled', models.BooleanField(default=True)),
                ('expiry_alert_enabled', models.BooleanField(default=True)),
                ('alert_days_before_expiry', models.IntegerField(default=30)),
                ('sms_report_enabled', models.BooleanField(default=True)),
                ('daily_report_time', models.TimeField(default='21:00:00')),
                ('enable_offline_mode', models.BooleanField(default=True)),
                ('offline_sync_interval', models.IntegerField(default=5)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='pharmacy.branch')),
            ],
            options={
                'verbose_name': 'Branch Settings',
                'verbose_name_plural': 'Branch Settings',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='pharmacy.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['registration_number'], name='pharmacy_ph_registr_50f817_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['license_number'], name='pharmacy_ph_license_48b72f_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['pharmacy', 'is_active'], name='pharmacy_br_pharmac_1ec191_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('pharmacy', 'code')},
        ),
    ]
