# Generated by Django 4.2.11 on 2026-06-23 21:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(help_text='e.g., Customer, Sale, Inventory', max_length=50)),
                ('entity_id', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('payload', models.JSONField(help_text='The serialized data')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='pharmacy.branch')),
            ],
            options={
                'verbose_name': 'Sync Queue Event',
                'verbose_name_plural': 'Sync Queue Events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['branch', 'status', 'created_at'], name='pharmacy_sy_branch__cf2c93_idx')],
            },
        ),
        migrations.CreateModel(
            name='BranchDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_identifier', models.CharField(help_text='Hardware MAC address or UUID', max_length=255, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('auth_token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='pharmacy.branch')),
            ],
            options={
                'verbose_name': 'Branch Device',
                'verbose_name_plural': 'Branch Devices',
                'indexes': [models.Index(fields=['auth_token'], name='pharmacy_br_auth_to_e163b1_idx'), models.Index(fields=['branch', 'is_active'], name='pharmacy_br_branch__fd764c_idx')],
            },
        ),
    ]
