# Generated by Django 4.2.8 on 2026-06-29 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0002_alter_pharmacy_name_syncqueue_branchdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('main', 'Main Branch'), ('satellite', 'Satellite'), ('warehouse', 'Warehouse')], default='satellite', max_length=20),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the client recorded this change', null=True),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='conflict_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='has_conflict',
            field=models.BooleanField(default=False, help_text='True if server data was newer than client_timestamp'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='syncqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('CONFLICT', 'Conflict')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BranchStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('invited_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Invitation'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('can_access_pos', models.BooleanField(default=True)),
                ('can_access_inventory', models.BooleanField(default=False)),
                ('can_access_transaction_history', models.BooleanField(default=False)),
                ('can_access_dues', models.BooleanField(default=False)),
                ('can_access_customers', models.BooleanField(default=False)),
                ('can_access_analytics', models.BooleanField(default=False)),
                ('can_access_accounting', models.BooleanField(default=False)),
                ('can_access_purchases', models.BooleanField(default=False)),
                ('can_access_prescriptions', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='pharmacy.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Staff',
                'verbose_name_plural': 'Branch Staff',
                'indexes': [models.Index(fields=['branch', 'status'], name='pharmacy_br_branch__185a5c_idx'), models.Index(fields=['invited_email'], name='pharmacy_br_invited_ec7732_idx')],
            },
        ),
    ]
