name: Render Keep-Alive Cron

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual trigger from UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Health Endpoint
        run: |
          echo "Pinging backend to prevent sleep..."
          curl -s -D - -o /dev/null "https://pharmacy-django-fj01.onrender.com/health/"
